const icons={search:'⌕',cart:'♧',arrow:'↗'};
const products=[
 {id:1,brand:'Apple',name:'iPhone 14 Pro',storage:'128 GB',color:'Deep Purple',price:48999,old:79900,tone:'#777083',grade:'Like new',tag:'BESTSELLER',rating:'4.9'},
 {id:2,brand:'Samsung',name:'Galaxy S23 Ultra',storage:'256 GB',color:'Phantom Black',price:52999,old:124999,tone:'#434c48',grade:'Like new',tag:'GREAT VALUE',rating:'4.8'},
 {id:3,brand:'Apple',name:'iPhone 13',storage:'128 GB',color:'Starlight',price:29999,old:59900,tone:'#e4e1d5',grade:'Excellent',tag:'POPULAR PICK',rating:'4.8'},
 {id:4,brand:'Google',name:'Pixel 8',storage:'128 GB',color:'Hazel',price:32999,old:75999,tone:'#9baca6',grade:'Like new',tag:'PRICE DROP',rating:'4.7'},
 {id:5,brand:'OnePlus',name:'OnePlus 12',storage:'256 GB',color:'Flowy Emerald',price:38999,old:64999,tone:'#688f7b',grade:'Excellent',tag:'JUST ARRIVED',rating:'4.8'},
 {id:6,brand:'Samsung',name:'Galaxy S22',storage:'128 GB',color:'Bora Purple',price:23999,old:52999,tone:'#b7a9c7',grade:'Good',tag:'UNDER ₹25K',rating:'4.6'},
 {id:7,brand:'Apple',name:'iPhone 15',storage:'128 GB',color:'Blue',price:45999,old:69900,tone:'#b6d3da',grade:'Like new',tag:'JUST ARRIVED',rating:'4.9'},
 {id:8,brand:'Google',name:'Pixel 7 Pro',storage:'128 GB',color:'Snow',price:27999,old:84999,tone:'#d9dedb',grade:'Excellent',tag:'GREAT VALUE',rating:'4.7'}
];
const money=n=>'₹'+n.toLocaleString('en-IN');
let cart=JSON.parse(localStorage.getItem('rephone-cart')||'[]'),brand='All phones',query='',sort='featured',saved=new Set(),selected=null;
function phone(p,hero=false){let samsung=p.brand==='Samsung',pixel=p.brand==='Google';return `<svg class="phone-svg ${hero?'hero-phone':''}" viewBox="0 0 220 300" role="img" aria-label="${p.name} in ${p.color}"><defs><linearGradient id="g${p.id}${hero}" x1="0" x2="1" y2="1"><stop stop-color="${p.tone}"/><stop offset="1" stop-color="${p.tone}" stop-opacity=".65"/></linearGradient><linearGradient id="s${p.id}${hero}" x2="1" y2="1"><stop stop-color="#181d2e"/><stop offset=".5" stop-color="#706187"/><stop offset="1" stop-color="#bcc6ef"/></linearGradient></defs><g transform="translate(22 12) rotate(-9 75 140)"><rect width="132" height="264" rx="22" fill="url(#g${p.id}${hero})" stroke="#ffffff" stroke-opacity=".5" stroke-width="2"/>${pixel?'<rect x="0" y="37" width="132" height="36" fill="#626c68"/><rect x="12" y="43" width="70" height="23" rx="12" fill="#161f22"/><circle cx="26" cy="55" r="8" fill="#344151"/><circle cx="63" cy="55" r="8" fill="#344151"/>':`<rect x="9" y="11" width="${samsung?52:66}" height="${samsung?94:72}" rx="16" fill="${p.tone}" stroke="#ffffff" stroke-opacity=".18"/>${(samsung?[[24,28],[24,56],[24,84],[51,42]]:[[27,30],[54,49],[26,65]]).map(([x,y])=>`<circle cx="${x}" cy="${y}" r="11" fill="#172126" stroke="#a2a1ab" stroke-width="2"/><circle cx="${x}" cy="${y}" r="5" fill="#293a4d"/>`).join('')}`}<text x="66" y="154" text-anchor="middle" fill="#fff" fill-opacity=".55" font-size="24">${p.brand==='Apple'?'●':p.brand==='Google'?'G':samsung?'':'1+'}</text></g><g transform="translate(110 47) rotate(9 50 120)"><rect width="104" height="225" rx="19" fill="#171c24" stroke="#7d8390" stroke-width="2"/><rect x="5" y="5" width="94" height="215" rx="15" fill="url(#s${p.id}${hero})"/><path d="M5 170 Q75 80 99 125 L99 218 L5 218Z" fill="#c4b6e0" fill-opacity=".5"/><rect x="33" y="10" width="39" height="10" rx="6" fill="#101519"/></g></svg>`}
document.querySelector('#app').innerHTML=`
<div class="announcement">A fresh start for great phones. <span>Quality checked. Honestly priced.</span><a href="#promise">Discover the Rephone promise ↗</a></div>
<header><a class="logo" href="#">rephone<span>✳</span></a><div class="searchbox"><span>⌕</span><input id="search" aria-label="Search phones" placeholder="Search your next upgrade"><kbd>/</kbd></div><div class="header-actions"><button id="help">◉ <span>Talk to an expert</span></button><button id="cart" aria-label="Open shopping bag">Bag <b id="count">0</b></button></div></header>
<nav><div class="navlinks"><a href="#shop" class="active">Shop all phones</a><a href="#shop" data-brand="Apple">Apple</a><a href="#shop" data-brand="Samsung">Samsung</a><a href="#shop" data-brand="Google">Google</a><a href="#shop" data-brand="OnePlus">OnePlus</a><a href="#promise">Our promise</a></div><span class="nav-note">✓ Every phone. Expert checked.</span></nav>
<main><section class="hero"><div class="hero-copy"><div class="eyebrow"><span></span> SMARTER PHONES. SMARTER PRICES.</div><h1>Your next upgrade.<br><em>Minus the big price.</em></h1><p>Flagship phones, with a fresh start. Discover expertly<br class="desktop"> checked pre-owned phones you’ll love to own.</p><div class="hero-buttons"><a class="primary" href="#shop">Find your phone <span>↗</span></a><a class="text-link" href="#promise">Why Rephone? ↗</a></div><div class="social-proof"><div class="avatars"><i>AK</i><i>RS</i><i>NP</i><i>MJ</i></div><div><strong>★★★★★</strong><small>Made for happy upgrades</small></div></div></div><div class="hero-art"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="spark spark-one">✦</span><span class="spark spark-two">✧</span><div class="floating-label"><span>✓</span><div>Looks like new.<br><b>Feels like a smart choice.</b></div></div>${phone(products[0],true)}<div class="price-float"><small>iPhone 14 Pro • Like new</small><b>${money(48999)} <span>${money(79900)}</span></b><em>Flagship feeling. Better price.</em></div><div class="art-caption">A SECOND LIFE. A FIRST-CLASS EXPERIENCE.</div></div></section>
<section class="benefits" id="promise"><div><i>◇</i><span><b>32-point quality check</b><small>Tested by experts, ready for you</small></span></div><div><i>◷</i><span><b>6-month store warranty</b><small>A little extra peace of mind</small></span></div><div><i>↺</i><span><b>7-day replacement</b><small>We’ll help make it right</small></span></div><div><i>♧</i><span><b>Visit. Try. Take it home.</b><small>Your local store, now online</small></span></div></section>
<section class="shop" id="shop"><div class="section-heading"><div><div class="eyebrow">THE UPGRADE EDIT</div><h2>Big on features. Easy on your pocket.</h2><p>Your favourite brands, at prices worth a second look.</p></div><a href="#shop" id="reset">Explore all phones ↗</a></div><div class="filterbar"><div class="chips">${['All phones','Apple','Samsung','Google','OnePlus'].map((b,i)=>`<button class="chip ${i===0?'selected':''}" data-brand="${b}">${b}</button>`).join('')}</div><label>Sort by: <select id="sort"><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div><div id="results-info" aria-live="polite"></div><div class="product-grid" id="products"></div></section>
<section class="concierge"><div class="concierge-icon">◉</div><div><div class="eyebrow">A REAL PERSON. A BETTER DECISION.</div><h2>Can’t decide? Let’s talk phones.</h2><p>Tell us your budget. We’ll help you find your perfect match on WhatsApp.</p></div><button class="primary" id="concierge">Chat with an expert ↗</button></section>
<section class="steps"><div><div class="eyebrow">FROM SCROLL TO STORE</div><h2>Your upgrade, made simple.</h2></div><article><span>01</span><h3>Find your favourite</h3><p>Explore phones by brand, budget and condition.</p></article><article><span>02</span><h3>Say hello on WhatsApp</h3><p>Send your selection. Ask questions. Check availability.</p></article><article><span>03</span><h3>Try it. Love it. Take it.</h3><p>Visit the store, inspect your phone and upgrade.</p></article></section></main>
<footer><div><a class="logo" href="#">rephone<span>✳</span></a><p>Great phones deserve a second story.</p></div><div><b>A smarter way to upgrade.</b><p>Pre-owned phones. Personal service. Real value.</p></div><small>Demo storefront · Sample inventory & policies<br>© ${new Date().getFullYear()} Rephone</small></footer><button class="whatsapp-fab" id="whatsapp" aria-label="Chat on WhatsApp">◉ <span>Let’s chat</span></button><div id="modal-root"></div><div class="toast" id="toast" role="status"></div>`;
function render(){let list=products.filter(p=>(brand==='All phones'||p.brand===brand)&&`${p.name} ${p.storage} ${p.color} ${p.grade}`.toLowerCase().includes(query));if(sort!=='featured')list.sort((a,b)=>sort==='low'?a.price-b.price:b.price-a.price);document.querySelector('#results-info').textContent=query?`${list.length} phones found for “${query}”`:'';document.querySelector('#products').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-art" data-detail="${p.id}"><span class="product-tag">${p.tag}</span><button class="save ${saved.has(p.id)?'saved':''}" data-save="${p.id}" aria-label="${saved.has(p.id)?'Unsave':'Save'} ${p.name}">${saved.has(p.id)?'♥':'♡'}</button>${phone(p)}<span class="grade"><i></i>${p.grade}</span></div><div class="product-info"><div class="brand-rating"><span>${p.brand}</span><b>★ ${p.rating}</b></div><button class="product-title" data-detail="${p.id}">${p.name}</button><p>${p.storage} <span>•</span> ${p.color}</p><div class="price">${money(p.price)} <del>${money(p.old)}</del></div><small class="saving">Save ${Math.round((1-p.price/p.old)*100)}% on your upgrade</small><button class="add-button" data-add="${p.id}">Add to bag <span>+</span></button></div></article>`).join(''):'<div class="empty">No phones found. Try another brand or search.</div>';document.querySelectorAll('.chip').forEach(el=>el.classList.toggle('selected',el.dataset.brand===brand));document.querySelector('#count').textContent=cart.length;localStorage.setItem('rephone-cart',JSON.stringify(cart));}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),2600)}
function close(){document.querySelector('#modal-root').innerHTML='';document.body.classList.remove('modal-open')}
function modal(content){document.querySelector('#modal-root').innerHTML=`<div class="overlay"><section class="dialog" role="dialog" aria-modal="true" aria-label="Phone enquiry"><button class="close" aria-label="Close dialog">×</button>${content}</section></div>`;document.body.classList.add('modal-open');document.querySelector('.close').focus()}
function chat(items=[]){let message=items.length?`Hi Rephone! I'm interested in:\n${items.map(p=>`${p.name} (${p.storage}, ${p.color}, ${p.grade}) — ${money(p.price)}`).join('\n')}\nTotal: ${money(items.reduce((s,p)=>s+p.price,0))}\nPlease confirm availability and store pickup details.`:'Hi Rephone! Please help me find a pre-owned phone within my budget.';modal(`<div class="dialog-eyebrow">WHATSAPP CONCIERGE</div><h2>Your enquiry is ready.</h2><p>We’ve prepared your message so the store knows exactly what you’re looking for.</p><textarea id="message" aria-label="Enquiry message">${message}</textarea><div class="demo-note">Demo setup: enter the store’s WhatsApp number to try the handoff. Your message opens in WhatsApp; it is not sent automatically.</div><label class="field-label">Store WhatsApp number (with country code)<input id="number" type="tel" placeholder="e.g. 919876543210" value="${localStorage.getItem('rephone-number')||''}"></label><button class="primary full" id="send">Continue to WhatsApp ↗</button><p id="validation" role="alert"></p>`)}
function bag(){const items=cart.map(id=>products.find(p=>p.id===id));modal(`<div class="dialog-eyebrow">YOUR NEXT UPGRADE</div><h2>Your shopping bag <span>(${items.length})</span></h2>${items.length?`<div class="bag-items">${items.map((p,i)=>`<div class="bag-item">${phone(p)}<div><b>${p.name}</b><small>${p.storage} · ${p.grade}</small><strong>${money(p.price)}</strong></div><button data-remove="${i}" aria-label="Remove ${p.name}">×</button></div>`).join('')}</div><div class="bag-total"><span>Estimated total</span><b>${money(items.reduce((s,p)=>s+p.price,0))}</b></div><p>Confirm availability and arrange store pickup with our team.</p><button class="primary full" id="checkout">Enquire on WhatsApp ↗</button>`:'<p>Your next favourite phone is waiting. Add a phone to get started.</p><button class="primary full close-bag">Explore phones ↗</button>'}`)}
document.addEventListener('click',e=>{let el=e.target.closest('[data-brand]');if(el){brand=el.dataset.brand;render()}el=e.target.closest('[data-save]');if(el){e.stopPropagation();let id=+el.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);render();return}el=e.target.closest('[data-add]');if(el){cart.push(+el.dataset.add);render();toast('Added to your bag — a smarter upgrade awaits.')}el=e.target.closest('[data-detail]');if(el){selected=products.find(p=>p.id===+el.dataset.detail);modal(`<div class="detail-art">${phone(selected)}</div><div class="dialog-eyebrow">${selected.brand} · ${selected.grade}</div><h2>${selected.name}</h2><p>${selected.storage} · ${selected.color}</p><div class="price">${money(selected.price)} <del>${money(selected.old)}</del></div><ul class="detail-list"><li>32-point hardware and functionality check</li><li>6-month demo store warranty</li><li>Inspect in store before purchasing</li></ul><p class="demo-note">Illustrative product image. Sample listing; actual battery health, accessories and availability confirmed by the store.</p><button class="primary full" id="detail-chat">Ask about this phone ↗</button>`)}if(e.target.closest('.close,.close-bag')||e.target.classList.contains('overlay'))close();if(e.target.closest('#cart'))bag();el=e.target.closest('[data-remove]');if(el){cart.splice(+el.dataset.remove,1);render();bag()}if(e.target.closest('#checkout'))chat(cart.map(id=>products.find(p=>p.id===id)));if(e.target.closest('#detail-chat'))chat([selected]);if(e.target.closest('#help,#whatsapp,#concierge'))chat();if(e.target.closest('#reset')){brand='All phones';query='';document.querySelector('#search').value='';render()}if(e.target.closest('#send')){let number=document.querySelector('#number').value.replace(/[\s+()-]/g,'');if(!/^\d{10,15}$/.test(number)){document.querySelector('#validation').textContent='Enter a valid number with country code (10–15 digits).';return}localStorage.setItem('rephone-number',number);window.open(`https://wa.me/${number}?text=${encodeURIComponent(document.querySelector('#message').value)}`,'_blank','noopener,noreferrer')}});
document.querySelector('#search').addEventListener('input',e=>{query=e.target.value.toLowerCase();render()});document.querySelector('#sort').addEventListener('change',e=>{sort=e.target.value;render()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();document.querySelector('#search').focus()}if(e.key==='Tab'&&document.querySelector('.dialog')){const focus=[...document.querySelector('.dialog').querySelectorAll('button,input,textarea,a')];if(e.shiftKey&&document.activeElement===focus[0]){e.preventDefault();focus.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===focus.at(-1)){e.preventDefault();focus[0].focus()}}});render();
